### PR TITLE
Documentation 

### LINKED ISSUE #2: Documentation
Assign me to this issue to add a README.

### PR DESCRIPTION
**Pull request by Itsfoss0**
This PR closes #2 
I have added 
* [X] README
* [ ] Unit test
* [X] Contributors

### CODE REVIEW

**Comment by Itsfoss0** [comment]
Hi, @Michelle-Wanderi 
Please review and merge. 
Let me know if there's any changes that are supposed to be done.

**Comment by Itsfoss0** [comment]
I'll start working on the console tomorrow.

**Review by Michelle-Wanderi — COMMENTED** [review]
Everything is explained perfectly

**Comment by Michelle-Wanderi** [comment]
> Hi, @Michelle-Wanderi Please review and merge. Let me know if there's any changes that are supposed to be done.
Okay. Working on that :+1:

**Review by Michelle-Wanderi — APPROVED** [review]

**Pull request merged**
