### PR TITLE
User Module and Test

### LINKED ISSUE #9: USER module
Handle everything __User__ related. 
From the __User__ class, to tests for the User module and handling FileStorage for this class.

### PR DESCRIPTION
**Pull request by Itsfoss0**
This PR closes #9 

* [X] I have ran unnitest on the module
* [X] All the test cases pass
* [X] My code is pycodesyle compliant
* [X] I have followed PEP-8 conventions
* [X] I have documented all my modules, classes, method and functions

### CODE REVIEW

**Review by Itsfoss0 — COMMENTED** [review]
Looking great. From what I can see, its ready to be merged.

Back to you @Michelle-Wanderi

**Review by Michelle-Wanderi — COMMENTED** [review]
Everything is okay

**Review by Michelle-Wanderi — COMMENTED** [review]
Some explanations are needed but good job really. I'll work on the others

**Review by Michelle-Wanderi — APPROVED** [review]

**Comment by Itsfoss0** [comment]
> Some explanations are needed but good job really. I'll work on the others

Sure. I'll be happy to explain the changes.

**Pull request merged**
